---
title: "wesad-model"
author: "Anna Darwish"
date: "9/27/2020"
output: html_document
---
## EDA Plots

```{r, function checking for installed packages, echo=FALSE, results="hide", include=FALSE}
# Validate that all necessary packaged have been downloaded, install otherwise or throw err package DNE
pkgTest <- function(x)
{
  if (!require(x,character.only = TRUE))
  {
    install.packages(x,repos = "http://cran.r-project.org", dep=TRUE)
    if(!require(x,character.only = TRUE)) stop("Package not found")
  }
}
```

```{r Package Test Libraries, echo=FALSE, results="hide", include=FALSE}
pkgTest("arm")
pkgTest("broom")
pkgTest("cowplot")
pkgTest("dplyr")
pkgTest("ggplot2")
pkgTest("knitr")
pkgTest("kableExtra")
pkgTest("MASS")
pkgTest("msm")
pkgTest("plotROC")
pkgTest("pROC")
pkgTest("tidyr")
```

```{r Load in Libraries, echo=FALSE, results="hide", include=FALSE}
library(arm)
library(broom)
library(cowplot)
library(dplyr)
library(ggplot2)
library(knitr)
library(kableExtra)
library(MASS)
library(msm)
library(plotROC)
library(pROC)
library(tidyr)
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
# ggplot2::theme_set(new = theme_bw())
```

```{r}
wesad <- read.csv("merged_wesad_data.csv")
MODEL_RESULTS = "wesad_models.txt"
set.seed(1234)
```

```{r}
ggplot(wesad) +
  geom_histogram(aes(x=EDA_CHEST_MEAN, fill=label), alpha = 0.6, position = "identity")+
  facet_wrap(~subject, ncol = 5, scales = "free")+
  labs(x = expression(paste("Electrodermal Activity (",mu,"S)")), title = "RespiBan - Electrodermal Activity")

ggplot(wesad) +
  geom_histogram(aes(x=Temp_CHEST_MEAN, fill=label),alpha = 0.6, position = "identity") +
  facet_wrap(~subject, ncol = 5, scales = "free") +
  labs(x = expression("Temperature " (degree*C)), title = "RespiBan - Body Temperature")

ggplot(wesad) +
  geom_histogram(aes(x=EDA_EMP4_STDDEV, fill=label), alpha = 0.6, position = "identity")+
  facet_wrap(~subject, ncol = 5, scales = "free")+
  labs(x = expression(paste("Electrodermal Activity (",mu,"S)")), title = "EMP4 - Electrodermal Activity")

ggplot(wesad) +
  geom_histogram(aes(x=TEMP_EMP4_MEAN, fill=label),alpha = 0.6, position = "identity") +
  facet_wrap(~subject, ncol = 5, scales = "free") +
  labs(x = expression("Temperature " (degree*C)), title = "EMP4 - Skin Temperature")
```

## Wrist & Chest Model

```{r Generate and Test Wrist and Chest Model, warning=F}
summary(wesad$EDA_CHEST_MEAN)
summary(wesad$EDA_EMP4_MEAN)
summary(wesad$Temp_CHEST_MEAN)

chan_bit=2^16
vcc=3
wesad$transformedEDACHEST <- wesad$EDA_CHEST_MEAN/chan_bit * vcc/0.12 * 1000000
summary(wesad$transformedEDACHEST) 

wesad$label <- as.factor(wesad$label)
# levels(wesad$label)[levels(wesad$label)=="Stressed"] <- 1
# levels(wesad$label)[levels(wesad$label)=="Amused"] <- 0

model.chest.final <- glm(label ~ EDA_CHEST_MEAN + Temp_CHEST_MEAN + subject, data = wesad, family = binomial)
summary(model.chest.final)
```

```{r Chest and Wrist Model Diagnostics}
threshold <- 0.5
model.chest.final <- augment(model.chest.final, type.predict = "response")
summary(wesad$label)
model.chest.final %>%
  mutate(stressed_predict = if_else(.fitted > threshold, "Stressed", "Amused")) %>%
  group_by(label, stressed_predict) %>%
  summarise(n = n()) %>%
  spread(label, n) %>%
  kable(format="markdown")

roc(model.chest.final$label,model.chest.final$.fitted)$auc

ggplot(model.chest.final, aes(d = as.numeric(label), m = .fitted)) + 
  geom_roc(n.cuts = 0) + 
  geom_abline(intercept = 0)

roc(model.chest.final$label,model.chest.final$.fitted)$auc

arm::binnedplot(x=model.chest.final$.fitted,y=model.chest.final$.resid,
                xlab="Predicted Probabilities", 
                main = "Binned Residual vs. Predicted Probabilities")

arm::binnedplot(x=model.chest.final$EDA_CHEST_MEAN,y=model.chest.final$.resid,
                xlab="RespiBAN Electrodermal Activity", 
                main = "Binned Residual vs. RespiBAN Electrodermal Activity")

arm::binnedplot(x=model.chest.final$Temp_CHEST_MEAN,y=model.chest.final$.resid,
                xlab="RespiBAN Body Temperature", 
                main = "Binned Residual vs. RespiBANBody Temperature")
```

```{r Cross Validation of Wrist and Chest Model, warning=F}
wesad_random<-wesad[sample(nrow(wesad)),]
folds <- cut(seq(1,nrow(wesad_random)), breaks=10, labels=FALSE)
accuracies = c()
random_selection_accuracies <- c()
for(i in 1:10){
  # Segement your data by fold using the which() function 
  test.indices <- which(folds==i,arr.ind=TRUE)
  test <- wesad_random[test.indices, ]
  train <- wesad_random[-test.indices, ]
  
  # Fitting the linear model using train data
  glm.fit <- glm(label ~ EDA_CHEST_MEAN + Temp_CHEST_MEAN + subject, data = train, family = binomial)
  
  # Calculating accuracy using test data
  glm.probs <- predict(glm.fit, test, type = "response")
  glm.pred <- rep("Amused", nrow(test))
  glm.pred[glm.probs > 0.5] <- "Stressed" # if prob > 0.5, predicted label = stressed
  
  # ensure randomized predictions for each fold with runif function
  set.seed(i)
  accuracies <- c(accuracies, (sum(diag(table(glm.pred, test$label)))/nrow(test)))
  
  stressed.proportion <- sum(as.numeric(test$label) - 1)/nrow(test)
  
  guess = 1
  if (stressed.proportion < 0.5){
    guess = 0
  }
  random.guesses = data.frame(actual=(as.numeric(test$label) - 1))
  random.guesses$estimates <- rep(guess,nrow(random.guesses))
  random_selection_accuracies <- c(random_selection_accuracies, (1-sum(abs(random.guesses$estimates-random.guesses$actual))/nrow(test)))
}

model_one_result = paste0("After performing 10-fold cross validation on our final model, the average accuracy rate on the test sets was: ",
                          round(mean(accuracies),3), 
                          " with the worst accuracy rate being ", round(min(accuracies),3), 
                          " and the best accuracy rate being ", round(max(accuracies),3), 
                          ". In contrast, predicting the most frequent class in the test set, yielded a mean accuracy of: ", round(mean(random_selection_accuracies),3), 
                          " with the worst accuracy rate being ", round(min(random_selection_accuracies),3), 
                          " and the best accuracy rate being ", round(max(random_selection_accuracies),3))

print(model_one_result)
write(model_one_result,file=MODEL_RESULTS,append=TRUE)
```

```{r Wrist Only Model}
model.wrist.final <- glm(label ~ EDA_EMP4_STDDEV + TEMP_EMP4_MEAN + subject, data = wesad, family = binomial)
step.model.wrist.final <- stepAIC(model.wrist.final, direction = "forward", trace=FALSE)
summary(step.model.wrist.final)
```

```{r Model Diagnostics of Wrist Only Model, warning=F}
threshold <- 0.5
final.model.wrist <- augment(model.wrist.final, type.predict = "response")

final.model.wrist %>%
  mutate(stressed_predict = if_else(.fitted > threshold, "Stressed", "Amused")) %>%
  group_by(label, stressed_predict) %>%
  summarise(n = n()) %>%
  spread(label, n) %>%
  kable(format="markdown")

ggplot(final.model.wrist, aes(d = as.numeric(label), m = .fitted)) + 
  geom_roc(n.cuts = 0) + 
  geom_abline(intercept = 0)

roc(final.model.wrist$label,final.model.wrist$.fitted)$auc

arm::binnedplot(x=final.model.wrist$.fitted,y=final.model.wrist$.resid,
                xlab="Predicted Probabilities", 
                main = "Binned Residual vs. Predicted Probabilities", col.int = FALSE)

arm::binnedplot(x=final.model.wrist$EDA_EMP4_STDDEV,y=final.model.wrist$.resid,
                xlab="Empatica E4 Electrodermal Activity Std Deviation",
                main = "Binned Residual vs. Electrodermal Activity", col.int = FALSE)

arm::binnedplot(x=final.model.wrist$TEMP_EMP4_MEAN,y=final.model.wrist$.resid,
                xlab="Empatica E4 Electrodermal Activity", 
                main = "Binned Residual vs. EMP4 Skin Temperature", col.int = FALSE)
```

```{r Wrist Model CV and Accuracy, warning=F}
wesad_random<-wesad[sample(nrow(wesad)),]
folds <- cut(seq(1,nrow(wesad_random)), breaks=10, labels=FALSE)
accuracies = c()
random_selection_accuracies <- c()
for(i in 1:10){
  # Segement your data by fold using the which() function 
  test.indices <- which(folds==i,arr.ind=TRUE)
  test <- wesad_random[test.indices, ]
  train <- wesad_random[-test.indices, ]
  
  # Fitting the linear model using train data
  glm.fit <- glm(label ~ EDA_EMP4_STDDEV + TEMP_EMP4_MEAN + subject, data = train, family = binomial)
  
  # Calculating accuracy using test data
  glm.probs <- predict(glm.fit, test, type = "response")
  glm.pred <- rep("Amused", nrow(test))
  glm.pred[glm.probs > 0.5] <- "Stressed" # if prob > 0.5, predicted label = stressed
  # ensure randomized predictions for each fold with runif function
  
  set.seed(i)
  accuracies <- c(accuracies, (sum(diag(table(glm.pred, test$label)))/nrow(test)))
  
  stressed.proportion <- sum(as.numeric(test$label) - 1)/nrow(test)
  
  random.guesses = data.frame(actual=(as.numeric(test$label) - 1))
  random.guesses$estimates <- runif(nrow(test),0,1)
  random.guesses <- random.guesses %>% mutate(estimates = case_when(estimates < (1 - stressed.proportion) ~ 0, TRUE ~ 1))
  random_selection_accuracies <- c(random_selection_accuracies, (1-sum(abs(random.guesses$estimates-random.guesses$actual))/nrow(test)))
}

model_wrist_result = paste0("After performing 10-fold cross validation on our final model, the average accuracy rate on the test sets was: ",
                            round(mean(accuracies),3), 
                            " with the worst accuracy rate being ", round(min(accuracies),3), 
                            " and the best accuracy rate being ", round(max(accuracies),3), 
                            ". In contrast, generating random probabilities, while using a cutoff based on the distribution of stressed and amused samples in the test set, yielded a mean accuracy of: ", round(mean(random_selection_accuracies),3), 
                            " with the worst accuracy rate being ", round(min(random_selection_accuracies),3), 
                            " and the best accuracy rate being ", round(max(random_selection_accuracies),3))

print(model_wrist_result)
write(model_wrist_result,file=MODEL_RESULTS,append=TRUE)
```


```{r Model Diagnostics of Wrist Only Model, warning=F}
final.model.interaction <- glm(label ~ TEMP_EMP4_MEAN * subject, data = wesad, family = binomial)
summary(final.model.interaction)

factor.subject6 <- exp(-35.84*0.01 + 83.11*0.01)
factor.subject4 <- exp(-35.84*0.01 - 28.6*0.01)

model.interaction.result = paste0("We noticed that some of the subjects' likelihood of being stressed had opposite relationships with respect to their recorded skin temperature from the wristband. For example subject 6 recorded higher skin temperatures during his stress condition while subject 4 recorded lower skin temperatures during his stress condition. In this summary output of our interaction model, you will note that subject's 6 positive interaction effect with temperature counteracts the main effect of temperature on the likelihood of stress. Specifically, for a 0.01 increase in degrees Celsius, we expect that the likelihood that subject 6 is stressed multiplies by a factor of ", round(factor.subject6,3),". However for subject 4, we expect that for a 0.01 increase in degrees Celsisus, their likelihood of being stressed multiplies by a factor of ", round(factor.subject4,3))
print(model.interaction.result)
write(model.interaction.result,file=MODEL_RESULTS,append=TRUE)
```



