---
title: "Wrist Model"
author: "Anna Darwish"
date: "9/20/2020"
output: html_document
---

```{r, function checking for installed packages, echo=FALSE, results="hide", include=FALSE}
# Validate that all necessary packaged have been downloaded, install otherwise or throw err package DNE
pkgTest <- function(x)
{
  if (!require(x,character.only = TRUE))
  {
    install.packages(x,repos = "http://cran.r-project.org", dep=TRUE)
    if(!require(x,character.only = TRUE)) stop("Package not found")
  }
}
```

```{r Package Test Libraries, echo=FALSE, results="hide", include=FALSE}
pkgTest("dplyr")
pkgTest("ggplot2")
pkgTest("tidyr")
pkgTest("knitr")
pkgTest("kableExtra")
```

```{r Load in Libraries, echo=FALSE, results="hide", include=FALSE}
library(dplyr)
library(ggplot2)
library(tidyr)
library(knitr)
library(kableExtra)
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
# ggplot2::theme_set(new = theme_bw())
```

```{r Chest Electrodermal Activity}
library(ggplot2)
library(wesanderson)
wesad <- read.csv("merged_down_wesad_2_3.csv")
metrics_string = "EMG	ECG_PEAKS	ECG	EDA	Temp	Resp_PEAKS	Resp	EDA_EMP4	HR_EMP4	HRV	TEMP_EMP4	EMG_RANGE	EMG_MEDIAN	EMG_TEN_PERCENTILE	EMG_NINETY_PERCENTILE	EMG_MEAN	EMG_STDDEV	ECG_MEAN	ECG_STDDEV	EDA_MEAN	EDA_STDDEV	Temp_MEAN	Temp_STDDEV	Resp_MEAN	Resp_STDDEV	EDA_EMP4_MEAN	EDA_EMP4_STDDEV	HR_EMP4_MEAN	HR_EMP4_STDDEV	TEMP_EMP4_MEAN	TEMP_EMP4_STDDEV	HRV_RMSSD	HRV_MEAN	HRV_STDDEV"
wesad$label <- as.factor(wesad$label)
levels(wesad$label)
metrics = strsplit(metrics_string, "\\s+")[[1]]
ggplot(wesad, aes_string(x="EMG")) + 
  geom_histogram(data=subset(wesad,label == "Stressed"),fill = "orange", alpha = 0.5) +
  geom_histogram(data=subset(wesad,label == "Amused"),fill = "blue", alpha = 0.5) +
  facet_wrap(~ subject, ncol = 2, scales = "free") + 
  labs(title=paste0("merged_down_wesad_2_3_larger_window")) + 
  theme(axis.ticks.x = element_blank())
ggplot(wesad, aes_string(x="EMG", color="label")) +
  geom_histogram(fill="white", position="dodge") +
  facet_wrap(~ subject, ncol = 2, scales = "free") + 
  labs(title=paste0("merged_down_wesad_2_3_larger_window")) + 
  theme(legend.position="top")
# ggplot(subset(wesad,cut == "Stress"), aes_string(x="EMG", fill="label")) + geom_histogram(alpha=0.5) + 
#           facet_wrap(~ subject, ncol = 2, scales = "free") + 
#           labs(title=paste0("merged_down_wesad_2_3_larger_window")) + 
#           scale_color_manual(values=wes_palette(n=2, name="Royal1")) + theme(axis.ticks.x = element_blank())
# for (t in titles){
#   # wesad_t = paste0("merged_down_wesad", t, ".csv")
#   wesad <- read.csv("merged_down_wesad_2_3.csv")
#   for (i in metrics){
#   print(ggplot(wesad, aes_string(x=i, fill="label")) + geom_histogram() + 
#           facet_wrap(~ subject, ncol = 2, scales = "free") + 
#           labs(title=paste0("merged_down_wesad_2_3_larger_window")) + 
#           scale_color_manual(values=wes_palette(n=2, name="Royal1")) + theme(axis.ticks.x = element_blank())) 
#   }
#   break
# }
data(diamonds)

ggplot(diamonds,aes(x=price)) + 

theme_bw()+

geom_histogram(data=subset(diamonds,cut == "Ideal"),fill = "red", alpha = 0.2) +

geom_histogram(data=subset(diamonds,cut == "Fair"),fill = "blue", alpha = 0.2) +

geom_histogram(data=subset(diamonds,cut == "Premium"),fill = "green", alpha = 0.2)
ggplot(wesad, aes_string(x="EMG", fill="label")) + geom_histogram() + 
          facet_wrap(~ subject, ncol = 2, scales = "free") + 
          labs(title=paste0("merged_down_wesad_2_3_larger_window")) + 
          scale_color_manual(values=wes_palette(n=2, name="Royal1")) + theme(axis.ticks.x = element_blank())
```



